export const GET_USERS  = "GET_USERS"
export const CREATE_USER  = "CREATE_USER"
export const GET_USER_BYID  = "GET_USER_BYID"
export const UPDATE_USER  = "UPDATE_USER"
export const GET_ROLES  = "GET_ROLES"
